name: Build and test

on:
  pull_request_target:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: CI
    env:
      TENDERLY_ACCESS_KEY: ${{secrets.TENDERLY_ACCESS_KEY}}
      TENDERLY_ACCOUNT_NAME: ${{secrets.TENDERLY_ACCOUNT_NAME}}
      TENDERLY_PROJECT_NAME: ${{secrets.TENDERLY_PROJECT_NAME}}
      TENDERLY_GET_BY_PROJECT_NAME: ${{secrets.TENDERLY_GET_BY_PROJECT_NAME}}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test
